const db = require('../database');
const PDFDocument = require('pdfkit');
const nodemailer = require('nodemailer');

exports.getAllReports = (req, res) => {
  let query = `
    SELECT r.*, i.title as incident_title, u.name as developer_name 
    FROM RCAReports r
    JOIN Incidents i ON r.incident_id = i.id
    JOIN Users u ON r.developer_id = u.id
  `;
  const params = [];

  let conditions = [];

  if (req.query.status) {
    if (req.query.status === 'All') {
      // Do nothing, show all
    } else {
      conditions.push('r.status = ?');
      params.push(req.query.status);
    }
  } else if (req.query.approved === 'true') {
    conditions.push("r.status = 'Approved' OR r.approved = 1");
  } else if (req.user.role === 'IT Manager') {
    conditions.push("r.status IN ('Submitted', 'Pending Review', 'Approved', 'Rejected')");
  }

  if (req.user.role === 'Developer') {
    conditions.push('r.developer_id = ?');
    params.push(req.user.id);
  }

  if (conditions.length > 0) {
    query += ' WHERE ' + conditions.join(' AND ');
  }

  query += ' ORDER BY r.created_at DESC';

  db.all(query, params, (err, rows) => {
    if (err) return res.status(500).json({ error: 'Database error' });
    res.json(rows);
  });
};

exports.getReportById = (req, res) => {
  const query = `
    SELECT r.*, i.title as incident_title, u.name as developer_name 
    FROM RCAReports r
    JOIN Incidents i ON r.incident_id = i.id
    JOIN Users u ON r.developer_id = u.id
    WHERE r.incident_id = ?
  `;
  db.get(query, [req.params.id], (err, row) => {
    if (err) {
      console.error(`[Backend Log] Database error retrieving report for Incident ID ${req.params.id}:`, err);
      return res.status(500).json({ error: `Database error: ${err.message}` });
    }
    if (!row) {
      console.warn(`[Backend Log] Report not found for Incident ID: ${req.params.id}`);
      return res.status(404).json({ error: `Report for Incident ID ${req.params.id} not found.` });
    }
    console.log(`[Backend Log] Report retrieved successfully for Incident ID: ${req.params.id}`);
    res.json(row);
  });
};

const generatePDF = (report) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    const buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const parseMarkdown = (markdownStr) => {
      const sections = {};
      if (!markdownStr) return sections;
      const chunks = markdownStr.split(/(?=\n#\s)/);
      chunks.forEach(chunk => {
        const match = chunk.match(/^\n?#\s+(.+)\n([\s\S]*)$/);
        if (match) {
          const title = match[1].trim().toLowerCase();
          const content = match[2].trim();
          if (title.includes('incident summary')) sections.summary = content;
          if (title.includes('timeline')) sections.timeline = content;
          if (title.includes('error')) sections.errors = content;
          if (title.includes('git diff')) sections.gitDiff = content;
          if (title.includes('root cause')) sections.rootCause = content;
          if (title.includes('impact')) sections.impact = content;
          if (title.includes('recommended fixes') || title.includes('fixes')) sections.fixes = content;
          if (title.includes('prevention')) sections.prevention = content;
        }
      });
      return sections;
    };

    const sections = parseMarkdown(report.markdown_report);

    let confidence = 0;
    if (sections.timeline) confidence += 30;
    if (sections.errors) confidence += 40;
    if (sections.gitDiff) confidence += 20;
    if (sections.rootCause) confidence += 10;
    if (confidence > 95) confidence = 95;

    // --- PAGE 1: COVER ---
    doc.rect(0, 0, doc.page.width, 120).fill('#0F172A');
    doc.fillColor('#FFFFFF').fontSize(36).text('IncidentIQ', 50, 45, { align: 'left' });
    
    doc.y = 160;
    doc.fillColor('#0F172A').fontSize(28).text('Root Cause Analysis Report');
    doc.moveDown(0.5);
    doc.fontSize(14).fillColor('#64748B').text(`Incident ID: ${report.incident_id || report.id || 'N/A'}`);
    doc.text(`Generated: ${new Date(report.created_at).toLocaleString()}`);
    doc.text(`Generated By: ${report.developer_name || 'AI Engine'}`);
    doc.text(`Team: Platform Operations`);
    doc.moveDown(2);

    let cy = doc.y + 20;
    doc.rect(50, cy, 500, 100).stroke('#E2E8F0');
    doc.fillColor('#0F172A').fontSize(12)
       .text('Severity:', 70, cy + 20).fillColor('#EF4444').text(report.severity_level || 'Unknown', 140, cy + 20)
       .fillColor('#0F172A').text('Confidence:', 300, cy + 20).fillColor('#2563EB').text(`${confidence}%`, 380, cy + 20)
       .fillColor('#0F172A').text('Status:', 70, cy + 60).fillColor('#10B981').text('Resolved', 140, cy + 60)
       .fillColor('#0F172A').text('Duration:', 300, cy + 60).fillColor('#0F172A').text('25 Minutes', 380, cy + 60);

    // --- PAGE 2: EXEC SUMMARY ---
    doc.addPage();
    doc.fillColor('#0F172A').fontSize(22).text('Executive Summary', 50, 50);
    doc.moveDown();
    
    doc.fontSize(14).fillColor('#0F172A').text('Incident Summary');
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor('#334155').text(sections.summary?.replace(/^[-*•]\s*/gm, '') || 'No summary available.', { lineGap: 4 });
    doc.moveDown(1.5);
    
    doc.fontSize(14).fillColor('#0F172A').text('Business Impact');
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor('#334155').text(sections.impact?.replace(/^[-*•]\s*/gm, '') || 'No impact recorded.', { lineGap: 4 });
    doc.moveDown(1.5);
    
    doc.fontSize(14).fillColor('#0F172A').text('Resolution Summary');
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor('#10B981').text('The incident has been fully resolved and stability is confirmed.', { lineGap: 4 });

    // --- PAGE 3: TIMELINE ---
    doc.addPage();
    doc.fillColor('#0F172A').fontSize(22).text('Timeline Analysis', 50, 50);
    doc.moveDown();
    let ty = doc.y;
    if (sections.timeline) {
      const lines = sections.timeline.split('\n').filter(l => l.trim().length > 0);
      lines.forEach(line => {
        if (ty > doc.page.height - 100) { doc.addPage(); ty = 50; }
        doc.rect(50, ty, 500, 30).fillAndStroke('#F8FAFC', '#E2E8F0');
        doc.fillColor('#0F172A').fontSize(12).text(line.replace(/^[-*]\s*/, '').substring(0, 80), 60, ty + 10);
        ty += 40;
      });
    } else {
      doc.fontSize(12).fillColor('#64748B').text('No timeline data available.', 50, ty);
    }

    // --- PAGE 4: EVIDENCE ---
    doc.addPage();
    doc.fillColor('#0F172A').fontSize(22).text('Evidence Analysis', 50, 50);
    doc.moveDown();
    
    const drawTable = (y, rows, colWidths) => {
       let currentY = y;
       rows.forEach((row, i) => {
         const isHeader = i === 0;
         if (currentY > doc.page.height - 100) { doc.addPage(); currentY = 50; }
         doc.rect(50, currentY, 500, 30).fillAndStroke(isHeader ? '#0F172A' : (i % 2 === 0 ? '#F8FAFC' : '#FFFFFF'), '#E2E8F0');
         doc.fillColor(isHeader ? '#FFFFFF' : '#0F172A').fontSize(12);
         let currentX = 60;
         row.forEach((col, j) => {
           doc.text(col, currentX, currentY + 10, { width: colWidths[j], height: 20, lineBreak: false });
           currentX += colWidths[j] + 10;
         });
         currentY += 30;
       });
       return currentY;
    };
    
    let evY = doc.y;
    const evidenceRows = [['Source', 'Finding']];
    if (sections.timeline) evidenceRows.push(['Timeline', 'Chronological anomalies detected']);
    if (sections.errors) evidenceRows.push(['Logs', sections.errors.split('\n')[0].replace(/^[-*]\s*/, '').substring(0, 60)]);
    if (sections.gitDiff) evidenceRows.push(['Git Diff', 'Code modifications detected in repository']);
    if (evidenceRows.length > 1) {
      evY = drawTable(evY, evidenceRows, [100, 370]);
    } else {
      doc.fontSize(12).fillColor('#64748B').text('No evidence found.', 50, evY);
      evY += 30;
    }

    // --- PAGE 5: ROOT CAUSE & 5 WHYS ---
    doc.addPage();
    doc.fillColor('#0F172A').fontSize(22).text('Root Cause Analysis', 50, 50);
    doc.moveDown();
    
    let ry = doc.y;
    doc.rect(50, ry, 500, 100).fillAndStroke('#FEF2F2', '#EF4444');
    doc.fillColor('#991B1B').fontSize(14).text('Root Cause', 60, ry + 15);
    doc.fillColor('#7F1D1D').fontSize(12).text(sections.rootCause?.replace(/^[-*]\s*/gm, '').substring(0, 200) || 'Unknown root cause', 60, ry + 40, { width: 480 });
    
    ry += 130;
    doc.fillColor('#0F172A').fontSize(18).text('Five Whys Analysis', 50, ry);
    ry += 30;
    
    let rootText = sections.rootCause?.replace(/^[-*]\s*/gm, '') || 'Service failure observed';
    const whys = [
      `Why 1: ${rootText.split('.')[0]}`,
      `Why 2: Underlying connection or resource exhaustion occurred.`,
      `Why 3: Load spike exceeded provisioned capacity limits.`,
      `Why 4: Configuration defaults were not tuned for high scale.`,
      `Why 5: Lack of pre-deployment scale testing.`
    ];
    
    whys.forEach(why => {
      if (ry > doc.page.height - 100) { doc.addPage(); ry = 50; }
      doc.rect(50, ry, 500, 40).fillAndStroke('#F8FAFC', '#E2E8F0');
      doc.fillColor('#0F172A').fontSize(12).text(why.substring(0, 80), 60, ry + 12);
      ry += 50;
    });

    // --- PAGE 6: ACTION PLAN ---
    doc.addPage();
    doc.fillColor('#0F172A').fontSize(22).text('Action Plan', 50, 50);
    doc.moveDown();
    
    let ay = doc.y;
    doc.fontSize(16).text('Recommended Fixes', 50, ay);
    ay += 30;
    const fixRows = [['Action', 'Priority', 'Owner']];
    if (sections.fixes) {
      sections.fixes.split('\n').filter(l => l.trim().length > 0).forEach(line => {
         fixRows.push([line.replace(/^[-*✓]\s*/, '').substring(0, 40), 'High', 'IT Ops']);
      });
    }
    ay = drawTable(ay, fixRows, [270, 80, 100]);
    
    ay += 40;
    if (ay > doc.page.height - 100) { doc.addPage(); ay = 50; }
    doc.fontSize(16).fillColor('#0F172A').text('Prevention Plan', 50, ay);
    ay += 30;
    const prevRows = [['Preventive Action', 'Status']];
    if (sections.prevention) {
      sections.prevention.split('\n').filter(l => l.trim().length > 0).forEach(line => {
         prevRows.push([line.replace(/^[-*\d.]+\s*/, '').substring(0, 60), 'Pending']);
      });
    }
    drawTable(ay, prevRows, [380, 80]);

    // --- FOOTERS ---
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc.fontSize(10).fillColor('#94A3B8').text(
        `Generated by IncidentIQ AI RCA Engine | Page ${i + 1}`,
        50,
        doc.page.height - 40,
        { align: 'center', width: 500 }
      );
    }

    doc.end();
  });
};

exports.downloadPdf = (req, res) => {
  db.get('SELECT r.*, i.title as incident_title FROM RCAReports r JOIN Incidents i ON r.incident_id = i.id WHERE r.incident_id = ?', [req.params.id], async (err, report) => {
    if (err || !report) return res.status(404).json({ error: 'Report not found' });

    try {
      const pdfBuffer = await generatePDF(report);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=RCA_Report_${req.params.id}.pdf`);
      res.send(pdfBuffer);
    } catch (error) {
      res.status(500).json({ error: 'Failed to generate PDF' });
    }
  });
};

exports.emailReport = (req, res) => {
  const { to, subject, message } = req.body;

  db.get('SELECT r.*, i.title as incident_title FROM RCAReports r JOIN Incidents i ON r.incident_id = i.id WHERE r.incident_id = ?', [req.params.id], async (err, report) => {
    if (err || !report) return res.status(404).json({ error: 'Report not found' });

    try {
      const pdfBuffer = await generatePDF(report);

      if (!process.env.SMTP_EMAIL || process.env.SMTP_EMAIL === 'your_email@gmail.com' || !process.env.SMTP_PASSWORD) {
        console.log('[MOCK EMAIL] Missing valid SMTP credentials in .env.');
        console.log(`[MOCK EMAIL] Pretending to send RCA Report to ${to}...`);
        console.log(`[MOCK EMAIL] Subject: ${subject}`);
        return res.json({ message: 'Intelligence transmitted successfully (Mocked)' });
      }

      let transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: process.env.SMTP_EMAIL,
          pass: process.env.SMTP_PASSWORD
        }
      });

      await transporter.sendMail({
        from: process.env.SMTP_EMAIL,
        to,
        subject,
        text: message,
        attachments: [
          {
            filename: `RCA_Report_${req.params.id}.pdf`,
            content: pdfBuffer
          }
        ]
      });

      res.json({ message: 'Intelligence transmitted successfully' });
    } catch (error) {
      console.error('Email error:', error);
      res.status(500).json({ error: 'Failed to transmit. Ensure SMTP credentials are correct.' });
    }
  });
};

exports.submitReport = (req, res) => {
  const { name, email, team, notes } = req.body;
  
  if (!name || !email || !team) {
    return res.status(400).json({ error: 'Name, Email, and Team are required fields.' });
  }

  const query = `
    UPDATE RCAReports 
    SET status = 'Submitted', 
        submit_name = ?, 
        submit_email = ?, 
        submit_team = ?, 
        submit_notes = ?, 
        submitted_at = CURRENT_TIMESTAMP 
    WHERE incident_id = ? AND developer_id = ?
  `;
  
  db.run(query, [name, email, team, notes || '', req.params.id, req.user.id], function(err) {
    if (err) return res.status(500).json({ error: 'Database error' });
    if (this.changes === 0) return res.status(404).json({ error: 'Report not found or not authorized' });
    res.json({ message: 'Submitted successfully' });
  });
};

exports.deleteReport = (req, res) => {
  if (req.user.role !== 'Developer') {
    return res.status(403).json({ error: 'Unauthorized' });
  }
  
  db.run('DELETE FROM RCAReports WHERE incident_id = ? AND developer_id = ?', [req.params.id, req.user.id], function(err) {
    if (err) return res.status(500).json({ error: 'Database error' });
    if (this.changes === 0) return res.status(404).json({ error: 'Report not found or not authorized' });
    
    db.run('DELETE FROM Incidents WHERE id = ?', [req.params.id]);
    
    res.json({ message: 'Report deleted permanently' });
  });
};

exports.approveReport = (req, res) => {
  if (req.user.role !== 'IT Manager') return res.status(403).json({ error: 'Unauthorized' });
  
  const { comment } = req.body;
  const managerName = req.user.name || 'Manager';
  db.run("UPDATE RCAReports SET status = 'Approved', approved = 1, manager_comment = ?, manager_name = ?, reviewed_at = CURRENT_TIMESTAMP WHERE incident_id = ?", [comment || '', managerName, req.params.id], function(err) {
    if (err) {
      console.error('[Approve Error]', err);
      return res.status(500).json({ error: 'Database error', details: err.message });
    }
    if (this.changes === 0) {
      return res.status(404).json({ error: 'Report not found' });
    }
    res.json({ message: 'Report approved' });
  });
};

exports.rejectReport = (req, res) => {
  if (req.user.role !== 'IT Manager') return res.status(403).json({ error: 'Unauthorized' });
  
  const { comment } = req.body;
  const managerName = req.user.name || 'Manager';
  if (!comment) return res.status(400).json({ error: 'Reason required for rejection' });
  db.run("UPDATE RCAReports SET status = 'Rejected', approved = 0, manager_comment = ?, manager_name = ?, reviewed_at = CURRENT_TIMESTAMP WHERE incident_id = ?", [comment, managerName, req.params.id], function(err) {
    if (err) {
      console.error('[Reject Error]', err);
      return res.status(500).json({ error: 'Database error', details: err.message });
    }
    if (this.changes === 0) {
      return res.status(404).json({ error: 'Report not found' });
    }
    res.json({ message: 'Report rejected' });
  });
};

exports.markNotified = (req, res) => {
  if (req.user.role !== 'Developer') return res.status(403).json({ error: 'Unauthorized' });
  db.run("UPDATE RCAReports SET notified = 1 WHERE incident_id = ? AND developer_id = ?", [req.params.id, req.user.id], function(err) {
    if (err) return res.status(500).json({ error: 'Database error' });
    res.json({ message: 'Marked as notified' });
  });
};
